### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/citizen-budget-website#10]
The boxes for the three circles on the left get cut off the page. The position of the circle when the box appears should be different for each column of circles. So for example the circle should be in the middle of the box for the middle column, to the right of the box for the right column and to the left of the box for the left circles. I hope this makes sense to you!

**Comment by claudioccm** [comment]
@lharv076 what you wrote makes total sense, but from a design stand-point, it doesn't make sense, hehe. I was using that design previously (the different position for the circle) because I was using the full-width modal box. Now, that we are using a much narrower box, it makes much more sense to have the box appear centralized under the circle. This is design/UX matter. Making the box centralized creates an instant connection between the box and the circle.

**Comment by lharv076** [comment]
That sounds good if it's centralized for each box. In the mock-up all the circles are on the right of the box.

**Comment by claudioccm** [comment]
This is how it should look like. I think the different screen sizes are causing some problems for us.

<img width="1425" alt="screen shot 2016-03-15 at 4 29 03 pm" src="https://cloud.githubusercontent.com/assets/1649373/13793071/876d4bcc-eacb-11e5-8cd1-c14186f2ef0a.png">

**Comment by lharv076** [comment]
It might be the screen size. It only affected the circles on the left though.
