### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/citizen-budget-website#11]
When I readjust the size of my browser window, a lot of things get messed up (who’s using logos, the sections disappear, etc.). I don't know if this is just because it's a mock-up environment.

**Comment by claudioccm** [comment]
@lharv076 
This is because the responsive part of the site is not there yet. The ideal process for this, is to finish all content edits first, and than I will work on the mobile compatibility. 

Ideally we would have finished the content edits before the french version, since now, every edits has to be done twice (EN, FR). If I do the mobile stuff now, it can add up more unnecessary complexity for these edits, and it will consume even more time.

**Comment by lharv076** [comment]
no problem, I figured it was a case like this. Agreed, this process has been backwards from the start! Lessons learned for sure :)
