### ISSUE TITLE
 Footer

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/citizen-budget-website#13]
- [x] Change “About” to “Developed by”
- [x] Under “Contact”, remove “Open North” and our physical address. We only want it to say “info@opennorth.ca”, “1-888-750-4908” and “@opennorth” that leads to our twitter page. These 3 items need to be white instead of grey, the rest of the footer content can stay grey.

**Comment by claudioccm** [comment]
@lharv076, can you confirm for me how to translate "Developed by" to french?

**Comment by lharv076** [comment]
Développé par

**Comment by lharv076** [comment]
Can you make the contact info (email, phone # and twitter handle) white instead of grey?

**Comment by claudioccm** [comment]
sure

**Comment by lharv076** [comment]
And this edit is still needed, and then I'll be able to show Joel and JN!

**Comment by claudioccm** [comment]
oops. OK.
