### ISSUE TITLE
Benefits

### ISSUE THREAD

**Issue by lharv076** [ClaudioMendoncaDesign/citizen-budget-website#17]
There's a tagline at the top that reads "The trend towards online budget consultation has been gaining considerable momentum in North America and elsewhere, with the vast majority of people now online."

Did you add that in yourself? It's not in the content doc so I don't think we'll need it.

I like your idea of taking certain sentences and making them more prominent, but I feel like the team will prefer to just have regular paragraphs.

I'll get their feedback on this before asking you to change anything. Stay tuned :)

**Comment by claudioccm** [comment]
I changed the layout for this page
