### ISSUE TITLE
Text edits (sorry!)

### ISSUE THREAD

**Issue by lharv076** [ClaudioMendoncaDesign/citizen-budget-website#19]
I made some edits to the content doc in suggestion mode so you can see the changes, but see the text in this comment if it's easier for you to just copy paste it.

**About section's tagline**
_I added "online" between "Budget" and "simulator" and removed the comma after "citizens" so it should read:_

Citizen Budget online simulator is used by over 50 cities; reaching 6 million citizens coast-to-coast to significantly boost their budget consultations.

**About section's first paragraph**
_I added "online" between "Budget" and "simulator" and removed the "s" at the end of "educates" and "solicits". The first paragraph should read:_

Citizen Budget online simulator is a powerful and innovative tool that helps you build better community relations, educate your residents and solicit their feedback on your budget consultation.

**Key features**
_The third bullet point in the left column, please replace with:_

Fully hosted, including programming, maintenance, and summary report; no IT requirements on your end

**Request a demo form**
_Remove "provide you with a quote or" from the first paragraph. The new paragraph should read:_

We would be happy to schedule a demo for you and your team. Our webinars are done over the phone and internet with a screen sharing software so that you and your team can follow along together or from separate locations. 

**Overview, under "Multiple Modules"**
_Replace "them" with "residents" in all the bulletpoints. New points should read:_
- Challenge residents to balance the budget, using real data
- Ask residents to prioritize spending on a large capital project or amongst a variety of capital projects
- Engage residents on costs and associated tax impacts of program and service spending
- Allow residents to vote on allocating dollars to their favourites projects via “Participatory Budgeting”

**Benefits**
_Remove the word "mainly" in the first paragraph's sentence "They are often poorly attended...". The first paragraph should read:_

Traditionally, governments have held public consultations to solicit feedback on
budgets, laws and projects. While these processes are beneficial to the community, traditional
consultations have significant limitations. A typical public consultation can be costly and
stretch over many months. They are often poorly attended and can attract vocal groups with specific interests who may not represent the average citizen's needs. This is where digital tools come into play.

I know text edits aren't ideal at this stage but we want it to be perfect!

**Comment by gmattar** [comment]
Done. Should I change something in the French version?
