### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by lharv076** [ClaudioMendoncaDesign/citizen-budget-website#23]
- [x] Make the circles faded and light up when the user hovers over them (like the current client logos are)
- [x] We feel that the boxes are very large and bulky. Can you make them as small as you can?

**Comment by lharv076** [comment]
@claudioccm Any specific reason we got rid of the coloured boxes?

**Comment by claudioccm** [comment]
@lharv076, yes. I made them lighter in colors, in order to make them less "bulky" as you requested. The "bulky" feel, is due to several reasons, and the color is one of them. I made several changes on the design of the boxes, so they could look "lighter".
