### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lharv076** [ClaudioMendoncaDesign/citizen-budget-website#26]
- [ ] Let's remove the twitter link and only have the phone number and the email there.
- [ ] There's a mistake in the phone number, it's 1-888-750-**4980**

**Comment by lharv076** [comment]
@claudioccm  The content is all pushed to the left. Can you space it back like it was?

**Comment by claudioccm** [comment]
@gmattar, this is happening because we have the Quebec logo on the french version. We will need have slightly different styles for each footer.
