### ISSUE TITLE
French Website - text edits

### ISSUE THREAD

**Issue by lharv076** [ClaudioMendoncaDesign/citizen-budget-website#32]
Hey,

No that the text is final for the English website, here are the same edits for the French one:

**1. Tagline**

_Add "en ligne" between "budgétaires" and "interactives" so that it reads:_

Des consultations budgétaires en ligne interactives et innovatrices

**2. About section**

_Remove comma between "citoyens" and "d'un océan à l'autre" so that it reads:_

Un simulateur budgétaire interactif utilisé par plus de 50 municipalités, rejoignant ainsi 6 millions de citoyens d’un océan à l’autre

_Add "en ligne" between "outil" and "puissant" in the first line of the first paragraph so that it reads:_

Budget Citoyen est un outil en ligne puissant et innovateur qui participe au développement des relations communautaires, qui éduque les citoyens et qui cible leurs priorités quant aux budgets de fonctionnement ou d’immobilisations.

**3. Fonctionnalités principales**

_Replace third point with the following text:_

L’hébergement sur nos serveurs, incluant la programmation, la maintenance et un rapport sommaire (aucune connaissance technique n’est requise de votre part)

**4. Demandez une démonstration**

_Remove "vous fournir une estimation ou de" from the first line so that it reads:

Nous serions heureux de prévoir une démonstration pour votre équipe. 

**5. Avantages**

_Remove the word "principalement" near the end of the first paragraph between "attirent" and "des groupes" so that the sentence reads:_

Les taux de participation sont souvent bas et les réunions attirent des groupes aux intérêts bien définis qui ne représentent pas toujours les besoins de la majorité des citoyens.

Note: I made these changes in "suggestion mode" in the FR content doc if you need a reference. 

Thanks!

**Comment by claudioccm** [comment]
@lharv076 - thanks! I will get this ready asap.
