### ISSUE TITLE
french version

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/citizen-budget-website#7]

**Comment by lharv076** [comment]
There are two spots where the new edits weren't incorporated. I made the text red in the [content doc](https://docs.google.com/document/d/1URq4NUUjun8FCPZjdIUMG0LePPeo-kX77GmB-tMsYIc/edit#)

**Comment by lharv076** [comment]
I don't know if you're just waiting for a final OK on the english version before going ahead with the french one, but just in case: The top left "Citizen Budget" should read "Budget Citoyen" (make sure there's a space between both words)
