### ISSUE TITLE
video sign-off

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/citizen-budget-website#9]

**Comment by lharv076** [comment]
Before we sign off on this, I want to confirm that the skip in one of the videos will disappear when we have the top quality.

**Comment by claudioccm** [comment]
@lharv076 - yes, the video will be perfect. Nothing weird will be there. Hehe

**Comment by lharv076** [comment]
Alright, then you have the OK to purchase the video as long as it will be perfect!!

**Comment by lharv076** [comment]
@claudioccm There's still some skips!!! it's gotta be smooth.
